import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Textarea } from '../../components/ui/Textarea';
import { apiErrorMessage, isApiError } from '../../services/api';
import { cmsV2Api, type CmsDocumentData, type CmsField, type CmsRelease, type CmsRevision } from './api';

export const CMS_V2_PAGE_OPTIONS = [
  ['home','Home'],['about','About'],['leadership','Leadership'],['contact','Contact'],['careers','Careers'],['csr','CSR'],['gallery','Gallery'],['history','History'],['media-center','Media Center'],['sustainability','Sustainability'],['lake-oil','Lake Oil'],['lake-aviation','Lake Aviation'],['lake-gas','Lake Gas'],['lake-lubes','Lake Lubes'],['lake-steel','Lake Steel'],['lake-trans','Lake Trans'],['atl','ATL'],['aficd','AFICD'],['aill','AILL'],['acfs','ACFS'],['assembly-tech','Assembly Tech'],['cross-country','Cross Country'],['gulf-aggregates','Gulf Aggregates'],['lake-agro','Lake Agro'],['agrinova-tech','Agrinova Tech'],['nextdrive-motors','NextDrive Motors'],['lake-buildings','Lake Buildings'],['lake-cylinders','Lake Cylinders'],['lake-pipes','Lake Pipes'],['lake-premix-cement','Lake Premix'],['ocean-galleria','Ocean Galleria'],['la-home','Lake Agro Home'],['la-projects','Lake Agro Projects'],['fleet','Lake Trans Fleet'],['station-locator','Station Locator'],['business-verticals','Business Verticals'],['companies','Companies'],['global','Global Content'],
] as const;
const names = new Map<string, string>(CMS_V2_PAGE_OPTIONS);
const clone = <T,>(value: T): T => structuredClone(value);
const display = (key: string) => key.replace(/([A-Z])/g, ' $1').replace(/[-_]/g, ' ').replace(/^./, (letter) => letter.toUpperCase());
function leaves(value: CmsField | undefined, prefix = ''): Array<[string, string | boolean]> { if (typeof value === 'string' || typeof value === 'boolean') return [[prefix, value]]; if (!value || Array.isArray(value)) return []; return Object.entries(value).flatMap(([key, item]) => leaves(item, prefix ? `${prefix}.${key}` : key)); }
function change(data: CmsDocumentData, path: string, value: string | boolean) { const result = clone(data) as Record<string, CmsField>; const parts = path.split('.'); let node = result; parts.forEach((part, index) => { if (index === parts.length - 1) node[part] = value; else { const item = node[part]; node[part] = item && typeof item === 'object' && !Array.isArray(item) ? clone(item) : {}; node = node[part] as Record<string, CmsField>; } }); return result; }

export function WebsiteContentPage() {
  const { documentKey = 'home' } = useParams(); const name = names.get(documentKey) ?? display(documentKey);
  const [data, setData] = useState<CmsDocumentData | null>(null); const [saved, setSaved] = useState<CmsDocumentData | null>(null); const [revision, setRevision] = useState<string | null>(null); const [revisions, setRevisions] = useState<CmsRevision[]>([]); const [releases, setReleases] = useState<CmsRelease[]>([]); const [status, setStatus] = useState('Loading content…'); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [publishing, setPublishing] = useState(false);
  const load = async () => { try { const [{ document }, versionResult, releaseResult] = await Promise.all([cmsV2Api.documentByKey(documentKey), cmsV2Api.versionsByKey(documentKey), cmsV2Api.releases()]); const draft = document.currentDraftRevision; setData(draft?.data ? clone(draft.data as CmsDocumentData) : null); setSaved(draft?.data ? clone(draft.data as CmsDocumentData) : null); setRevision(draft?.id ?? null); setRevisions(versionResult.revisions); setReleases(releaseResult.releases); setStatus(draft ? 'Saved' : 'No imported draft exists yet'); } catch (cause) { setError(apiErrorMessage(cause)); setStatus('Could not load content'); } };
  useEffect(() => { void load(); }, [documentKey]); const dirty = useMemo(() => Boolean(data && saved && JSON.stringify(data) !== JSON.stringify(saved)), [data, saved]);
  const save = async () => { if (!data) return; setSaving(true); try { const result = await cmsV2Api.saveDraftByKey(documentKey, data, revision); setRevision(result.revision.id); setSaved(clone(data)); setRevisions((await cmsV2Api.versionsByKey(documentKey)).revisions); setStatus('Saved'); } catch (cause) { setError(isApiError(cause) && cause.code === 'REVISION_CONFLICT' ? 'This content changed after you opened it. Reload the latest version before saving.' : apiErrorMessage(cause)); setStatus('Save failed'); } finally { setSaving(false); } };
  const restore = async (id: string) => { try { const { revision: restored } = await cmsV2Api.restoreRevisionByKey(documentKey, id); const { document } = await cmsV2Api.documentByKey(documentKey); setRevision(restored.id); setData(document.currentDraftRevision?.data ? clone(document.currentDraftRevision.data as CmsDocumentData) : null); setSaved(document.currentDraftRevision?.data ? clone(document.currentDraftRevision.data as CmsDocumentData) : null); setRevisions((await cmsV2Api.versionsByKey(documentKey)).revisions); setStatus('Saved restored revision'); } catch (cause) { setError(apiErrorMessage(cause)); } };
  const publish = async () => { if (!revision || dirty) { setError('Save the current changes before publishing.'); return; } setPublishing(true); try { const { release } = await cmsV2Api.publishByKey(documentKey, revision); setReleases((items) => [release, ...items]); setStatus(`Published successfully · ${release.id}`); } catch (cause) { setError(apiErrorMessage(cause)); } finally { setPublishing(false); } };
  if (!data) return <Card><CardContent><p className="text-sm text-ink-muted">{status}</p>{error && <p className="mt-2 text-sm text-red-700">{error}</p>}<p className="mt-3 text-sm text-ink-muted">This page is registered. Its approved static content is imported during CMS data setup before the first draft.</p></CardContent></Card>;
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4 border-b border-border pb-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Website Pages</p><h1 className="mt-1 text-2xl font-semibold text-ink">{name}</h1><p className="mt-1 text-sm text-ink-muted">Structured content only. Layout, CSS, and components remain code-controlled.</p></div><div className="flex flex-wrap items-center gap-2"><span className={dirty ? 'text-sm font-medium text-amber-800' : 'text-sm font-medium text-emerald-700'}>{status}</span><Button loading={saving} onClick={() => void save()}>Save draft</Button><Button loading={publishing} disabled={!revision || dirty} onClick={() => void publish()}>Publish</Button></div></div>{error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><Card><CardHeader><CardTitle>Approved content fields</CardTitle><CardDescription>Text, safe links, media references, lists, and SEO are editable; design controls are not.</CardDescription></CardHeader><CardContent className="grid gap-4">{leaves(data).map(([path, value]) => <label key={path} className="grid gap-1.5 text-sm font-medium text-ink">{display(path)}{typeof value === 'boolean' ? <input className="h-4 w-4" type="checkbox" checked={value} onChange={(event) => setData(change(data, path, event.target.checked))} /> : value.length > 120 ? <Textarea rows={4} value={value} onChange={(event) => setData(change(data, path, event.target.value))} /> : <Input value={value} onChange={(event) => setData(change(data, path, event.target.value))} />}</label>)}</CardContent></Card><aside className="space-y-5"><Card><CardHeader><CardTitle>Publishing</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-ink-muted"><p>Public hydration remains disabled.</p><p>Current draft: <span className="font-mono text-xs text-ink">{revision ?? 'None'}</span></p><p>Latest release: {releases[0]?.publishedAt ? new Date(releases[0].publishedAt).toLocaleString() : 'Not published'}</p></CardContent></Card><Card><CardHeader><CardTitle>Revision history</CardTitle></CardHeader><CardContent><ul className="space-y-3">{revisions.map((item) => <li key={item.id} className="border-b border-border pb-3 last:border-0"><p className="break-all font-mono text-xs text-ink">{item.id}</p><p className="mt-1 text-xs text-ink-muted">{new Date(item.createdAt).toLocaleString()} · {item.authorId ?? 'System'}</p>{item.id !== revision && <Button size="sm" variant="outline" className="mt-2" onClick={() => void restore(item.id)}>Restore</Button>}</li>)}</ul></CardContent></Card><Link className="text-sm font-medium text-brand-700 hover:underline" to="/app">Back to overview</Link></aside></div></div>;
}
