import React, { Suspense, useEffect, useMemo, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { useTexture } from '@react-three/drei';
import * as THREE from 'three';

type Place = { id: string; name: string; lat: number; lng: number; flag: string; desktop: [number, number]; mobile: [number, number]; altitude: number };

const PLACES: Place[] = [
  { id:'tz', name:'TANZANIA', lat:-6.7924, lng:39.2083, flag:'tz', desktop:[68,18], mobile:[38,24], altitude:0 },
  { id:'ke', name:'KENYA', lat:-1.2921, lng:36.8219, flag:'ke', desktop:[72,-38], mobile:[42,-34], altitude:.055 },
  { id:'ug', name:'UGANDA', lat:.3476, lng:32.5825, flag:'ug', desktop:[-112,-52], mobile:[-82,-48], altitude:.07 },
  { id:'rw', name:'RWANDA', lat:-1.9441, lng:30.0619, flag:'rw', desktop:[-104,-8], mobile:[-78,-6], altitude:.075 },
  { id:'bi', name:'BURUNDI', lat:-3.3614, lng:29.3599, flag:'bi', desktop:[-108,26], mobile:[-80,28], altitude:.08 },
  { id:'cd', name:'DR CONGO', lat:-4.4419, lng:15.2663, flag:'cd', desktop:[-142,4], mobile:[-104,2], altitude:.115 },
  { id:'zm', name:'ZAMBIA', lat:-15.3875, lng:28.3228, flag:'zm', desktop:[-124,52], mobile:[-92,50], altitude:.105 },
  { id:'mz', name:'MOZAMBIQUE', lat:-25.9692, lng:32.5732, flag:'mz', desktop:[58,54], mobile:[34,50], altitude:.135 },
  { id:'et', name:'ETHIOPIA', lat:9.03, lng:38.74, flag:'et', desktop:[72,-44], mobile:[42,-42], altitude:.13 },
  { id:'ae', name:'UAE', lat:24.4539, lng:54.3773, flag:'ae', desktop:[88,-72], mobile:[50,-68], altitude:.2 },
];
const RADIUS=2, FINAL_ROTATION=4.36, LOOP_SECONDS=19;
const APPROVED_START_ROTATIONS=[FINAL_ROTATION-1.82,FINAL_ROTATION+1.66,FINAL_ROTATION-2.48,FINAL_ROTATION+2.32];
function chooseStartRotation(){const requested=Number(new URLSearchParams(location.search).get('globeStart')),random=globalThis.crypto?.getRandomValues?globalThis.crypto.getRandomValues(new Uint32Array(1))[0]/0xffffffff:Math.random(),index=Number.isInteger(requested)&&requested>=0?requested%APPROVED_START_ROTATIONS.length:Math.floor(random*APPROVED_START_ROTATIONS.length);return APPROVED_START_ROTATIONS[index]}
const START_ROTATION=chooseStartRotation();

function geoVector(lat:number,lng:number,radius=RADIUS){const phi=THREE.MathUtils.degToRad(90-lat),theta=THREE.MathUtils.degToRad(lng+180);return new THREE.Vector3(-radius*Math.sin(phi)*Math.cos(theta),radius*Math.cos(phi),radius*Math.sin(phi)*Math.sin(theta))}
function routePoints(destination:Place){const start=geoVector(PLACES[0].lat,PLACES[0].lng,1).normalize(),end=geoVector(destination.lat,destination.lng,1).normalize(),angle=start.angleTo(end),samples=96;return Array.from({length:samples},(_,index)=>{const t=index/(samples-1),sinAngle=Math.sin(angle),direction=sinAngle<.0001?start.clone():start.clone().multiplyScalar(Math.sin((1-t)*angle)/sinAngle).add(end.clone().multiplyScalar(Math.sin(t*angle)/sinAngle)),lift=Math.sin(Math.PI*t)*destination.altitude;return direction.normalize().multiplyScalar(RADIUS*(1.008+lift))})}

function Atmosphere(){const material=useMemo(()=>new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{color:{value:new THREE.Color('#7cc7e6')}},vertexShader:`varying vec3 n;varying vec3 p;void main(){n=normalize(normalMatrix*normal);p=(modelViewMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*vec4(p,1.);}`,fragmentShader:`uniform vec3 color;varying vec3 n;varying vec3 p;void main(){float f=pow(1.-abs(dot(n,normalize(-p))),3.6);gl_FragColor=vec4(color,f*.19);}`}),[]);useEffect(()=>()=>material.dispose(),[material]);return <mesh scale={1.045}><sphereGeometry args={[RADIUS,96,64]}/><primitive object={material} attach="material"/></mesh>}

type DomRefs = React.MutableRefObject<Record<string, HTMLElement | SVGLineElement | null>>;

function RuntimePause(){const setFrameloop=useThree(state=>state.setFrameloop),gl=useThree(state=>state.gl);useEffect(()=>{let onscreen=true;const sync=()=>setFrameloop(document.hidden||!onscreen?'never':'always'),target=gl.domElement.closest('.experience');const observer=target&&'IntersectionObserver'in window?new IntersectionObserver(entries=>{onscreen=entries[0]?.isIntersecting??true;sync()},{rootMargin:'120px'}):null;observer?.observe(target!);document.addEventListener('visibilitychange',sync);sync();return()=>{observer?.disconnect();document.removeEventListener('visibilitychange',sync)}},[gl,setFrameloop]);return null}

function Scene({reduced,labelRefs,leaderRefs}:{reduced:boolean;labelRefs:DomRefs;leaderRefs:DomRefs}){
  const {camera,size,gl}=useThree(),group=useRef<THREE.Group>(null),timeline=useRef(reduced?12:0),markerRefs=useRef<(THREE.Mesh|null)[]>([]),routeRefs=useRef<(THREE.Line|null)[]>([]),drag=useRef({active:false,id:-1,x:0,y:0}),userOffset=useRef({active:false,x:0,y:0,lastInput:0,decay:0}),automatedRotation=useRef({x:-.04,y:FINAL_ROTATION});
  const day=useTexture('assets/images/globe/earth_day.webp'),bump=useTexture('assets/images/globe/earth_topology.webp'),routes=useMemo(()=>PLACES.slice(1).map(routePoints),[]),routeObjects=useMemo(()=>routes.map(points=>{const geometry=new THREE.BufferGeometry().setFromPoints(points);geometry.setDrawRange(0,reduced?96:0);return new THREE.Line(geometry,new THREE.LineBasicMaterial({color:'#fff200',transparent:true,opacity:.68}))}),[reduced,routes]);
  useEffect(()=>{day.colorSpace=THREE.SRGBColorSpace;day.anisotropy=Math.min(8,gl.capabilities.getMaxAnisotropy());bump.anisotropy=Math.min(4,gl.capabilities.getMaxAnisotropy());gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.18;camera.position.set(0,.05,size.width<600?9.3:6.3);camera.lookAt(0,-.08,0)},[bump,camera,day,gl,size.width]);
  useEffect(()=>{const canvas=gl.domElement;canvas.style.touchAction='pan-y';const down=(event:PointerEvent)=>{if(event.button!==0||!group.current)return;userOffset.current={active:true,x:group.current.rotation.x-automatedRotation.current.x,y:group.current.rotation.y-automatedRotation.current.y,lastInput:performance.now(),decay:0};drag.current={active:true,id:event.pointerId,x:event.clientX,y:event.clientY};canvas.setPointerCapture?.(event.pointerId);canvas.classList.add('is-dragging')},move=(event:PointerEvent)=>{const current=drag.current;if(!current.active||current.id!==event.pointerId)return;const dx=event.clientX-current.x,dy=event.clientY-current.y;current.x=event.clientX;current.y=event.clientY;userOffset.current.y+=dx*.007;userOffset.current.x=THREE.MathUtils.clamp(userOffset.current.x+dy*.003,-.34,.24);userOffset.current.lastInput=performance.now()},up=(event:PointerEvent)=>{if(drag.current.id!==event.pointerId)return;drag.current.active=false;userOffset.current.active=false;userOffset.current.decay=1;canvas.releasePointerCapture?.(event.pointerId);canvas.classList.remove('is-dragging')};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);return()=>{canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up)}},[gl]);
  useEffect(()=>()=>routeObjects.forEach(line=>{line.geometry.dispose();line.material.dispose()}),[routeObjects]);
  useFrame((_,delta)=>{
    if(!group.current)return;
    timeline.current=reduced?12:(timeline.current+Math.min(delta,.2))%LOOP_SECONDS;
    const elapsed=Math.max(0,timeline.current),travel=THREE.MathUtils.smoothstep(elapsed,2,8),retract=1-THREE.MathUtils.smoothstep(elapsed,15,17);
    const phase=reduced?'hold':elapsed<2?'clean':elapsed<6?'rotate':elapsed<8?'africa-centered':elapsed<12?(elapsed<10?'reveal':'reveal-mid'):elapsed<15?'hold':elapsed<17?'retract':'clean';
    const panel=gl.domElement.closest('.experience-3d-panel') as HTMLElement|null;if(panel&&panel.dataset.globePhase!==phase)panel.dataset.globePhase=phase;
    camera.position.set(0,.05,size.width<600?9.3:6.3);camera.lookAt(0,-.08,0);
    automatedRotation.current={x:THREE.MathUtils.lerp(-.04,0,travel),y:FINAL_ROTATION+travel*(Math.PI*2)};
    const offset=userOffset.current;
    if(offset.active){group.current.rotation.y=automatedRotation.current.y+offset.y;group.current.rotation.x=THREE.MathUtils.clamp(automatedRotation.current.x+offset.x,-.34,.24)}
    else if(offset.decay>0){offset.decay=Math.max(0,offset.decay-.03*Math.min(delta,.2));group.current.rotation.y=automatedRotation.current.y+offset.y*offset.decay;group.current.rotation.x=THREE.MathUtils.clamp(automatedRotation.current.x+offset.x*offset.decay,-.34,.24)}
    else{offset.x=0;offset.y=0;group.current.rotation.y=automatedRotation.current.y;group.current.rotation.x=automatedRotation.current.x}
    const originOn=THREE.MathUtils.smoothstep(elapsed,7.9,8.25)*retract;markerRefs.current.forEach((mesh,index)=>{if(!mesh)return;const start=8.2+(index-1)*.41,active=index===0?originOn:THREE.MathUtils.smoothstep(elapsed,start,start+.28)*retract;mesh.scale.setScalar(active*(index===0?1.18:1))});
    routeRefs.current.forEach((line,index)=>{if(!line)return;const start=8.15+index*.41,progress=THREE.MathUtils.smoothstep(elapsed,start,start+.38)*retract;line.geometry.setDrawRange(0,Math.max(0,Math.floor(progress*96)))});
    const occupied:{left:number;right:number;top:number;bottom:number}[]=[];
    PLACES.forEach((place,index)=>{const label=labelRefs.current[place.id] as HTMLElement|null,leader=leaderRefs.current[place.id] as SVGLineElement|null;if(!label||!leader)return;const world=geoVector(place.lat,place.lng,RADIUS*1.018).applyEuler(group.current!.rotation),visible=world.clone().normalize().dot(camera.position.clone().normalize())>.08,reveal=index===0?originOn:THREE.MathUtils.smoothstep(elapsed,8.3+(index-1)*.41,8.58+(index-1)*.41)*retract,projected=world.clone().project(camera),x=(projected.x*.5+.5)*size.width,y=(-projected.y*.5+.5)*size.height,offset=size.width<600?place.mobile:place.desktop,width=label.offsetWidth,height=label.offsetHeight,candidates=[offset,[offset[0],offset[1]-18],[offset[0],offset[1]+18]] as [number,number][],overlap=(a:{left:number;right:number;top:number;bottom:number},b:{left:number;right:number;top:number;bottom:number})=>!(a.right+5<=b.left||a.left>=b.right+5||a.bottom+5<=b.top||a.top>=b.bottom+5);let chosen=candidates[0],chosenRect={left:0,right:0,top:0,bottom:0},best=Infinity;candidates.forEach(candidate=>{const left=THREE.MathUtils.clamp(x+candidate[0],8,Math.max(8,size.width-width-8)),top=THREE.MathUtils.clamp(y+candidate[1],8,Math.max(8,size.height-height-8)),rect={left,right:left+width,top,bottom:top+height},score=occupied.reduce((total,other)=>total+(overlap(rect,other)?10000:0),0)+Math.abs(candidate[1]-offset[1]);if(score<best){best=score;chosen=[left-x,top-y];chosenRect=rect}});occupied.push(chosenRect);const lx=chosenRect.left,ly=chosenRect.top,endX=chosen[0]>=0?lx-6:lx+width+6,endY=ly+height/2;label.style.transform=`translate3d(${lx}px,${ly}px,0)`;label.style.opacity=visible?String(reveal):'0';leader.setAttribute('x1',String(x));leader.setAttribute('y1',String(y));leader.setAttribute('x2',String(endX));leader.setAttribute('y2',String(endY));leader.style.opacity=visible?String(reveal*.58):'0'})
  });
  return <><RuntimePause/><ambientLight intensity={.78} color="#cbe5f2"/><hemisphereLight args={['#b7dff1','#06111d',.42]}/><directionalLight position={[4.8,2.4,5.6]} intensity={2.3} color="#fff7df"/><directionalLight position={[-4.6,-.4,1.6]} intensity={.74} color="#5c9bc4"/><group ref={group} rotation={[0,FINAL_ROTATION,0]}><mesh><sphereGeometry args={[RADIUS,128,96]}/><meshStandardMaterial map={day} bumpMap={bump} bumpScale={.035} color="#c4d2d8" emissive="#0a2234" emissiveIntensity={.42} roughness={.88} metalness={0}/></mesh>{routeObjects.map((line,index)=><primitive key={PLACES[index+1].id} object={line} ref={(value:THREE.Line|null)=>{routeRefs.current[index]=value}}/>)}{PLACES.map((place,index)=><mesh key={place.id} position={geoVector(place.lat,place.lng,RADIUS*1.012)} ref={(value)=>{markerRefs.current[index]=value}} scale={reduced?(index===0?1.12:1):0}><sphereGeometry args={[index===0?.022:.016,16,16]}/><meshBasicMaterial color="#fff200" toneMapped={false}/></mesh>)}</group><Atmosphere/></>
}

function GlobeMaster(){const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches||new URLSearchParams(location.search).has('final'),labelRefs=useRef<Record<string,HTMLElement|null>>({}),leaderRefs=useRef<Record<string,SVGLineElement|null>>({});return <main className="experience" aria-label="Lake Group global network centered on Tanzania"><Canvas dpr={[1,1.5]} camera={{fov:43,near:.1,far:100}} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}} onCreated={({gl})=>{gl.setClearColor(0x000000,0)}}><Suspense fallback={null}><Scene reduced={reduced} labelRefs={labelRefs as DomRefs} leaderRefs={leaderRefs as DomRefs}/></Suspense></Canvas><svg className="leaders" aria-hidden="true">{PLACES.map(place=><line key={place.id} data-leader={place.id} ref={node=>{leaderRefs.current[place.id]=node}}/>)}</svg><div className="labels" aria-hidden="true">{PLACES.map(place=><div className={`map-label ${place.id==='tz'?'origin':''}`} data-label={place.id} key={place.id} ref={node=>{labelRefs.current[place.id]=node}}><img src={`assets/images/flags/${place.flag}.svg`} alt=""/><span>{place.name}</span></div>)}</div><div className="sr-only">Lake Group locations: {PLACES.map(place=>place.name).join(', ')}. Every route begins in Dar es Salaam, Tanzania.</div></main>}
const mountNode=document.getElementById('root')??document.getElementById('hero-globe-root');
if(mountNode){const reactRoot=createRoot(mountNode);reactRoot.render(<GlobeMaster/>);window.addEventListener('pagehide',()=>reactRoot.unmount(),{once:true})}
