import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { IconArrowLeft, IconChevronDown, IconChevronRight, IconCopy, IconDeviceDesktop, IconDeviceMobile, IconDeviceTablet, IconDeviceFloppy, IconEye, IconEyeOff, IconLock, IconPlus, IconRefresh, IconSearch, IconTrash } from '@tabler/icons-react';
import { apiErrorMessage, isApiError } from '../../services/api';
import { controlApi, type ContentData, type ControlPage, type ReleaseReview, type Revision } from './api';
import { componentRegistry, compositionDiff, compositionFromLegacy, duplicateNode, effectiveLayout, findNode, insertNode, makeNode, moveNode, parentList, removeNode, renderComposition, resetResponsive, setResponsiveLayout, updateNode, type ComponentType, type Composition, type CompositionNode, type NodeLayout, type Viewport } from './composition';

const copy=<T,>(value:T):T=>structuredClone(value);
const safeLink=(value:string,action='internal')=>{if(!value||value.startsWith('//')||/[\u0000-\u001f\\]/.test(value))return false;try{const url=new URL(value,'https://lakegroup.invalid/');return ['http:','https:'].includes(url.protocol)||(action==='email'&&url.protocol==='mailto:')||(action==='telephone'&&url.protocol==='tel:')||(action==='anchor'&&value.startsWith('#'));}catch{return false;}};
function reorder(composition:Composition,sourceId:string,targetId:string){const next=copy(composition),source=parentList(next,sourceId),target=parentList(next,targetId);if(source!==target)return next;const from=source.findIndex(n=>n.id===sourceId),to=target.findIndex(n=>n.id===targetId);if(from<0||to<0)return next;const [node]=source.splice(from,1);source.splice(to,0,node);return next;}

function Layer({node,selected,expanded,toggle,select,action,drop}:{node:CompositionNode;selected:string;expanded:Set<string>;toggle:(id:string)=>void;select:(id:string)=>void;action:(name:string,id:string)=>void;drop:(source:string,target:string)=>void}){
 const open=expanded.has(node.id),hasChildren=node.children.length>0;
 return <div className="composer-layer"><div className={`composer-layer-row${selected===node.id?' is-selected':''}`} draggable={!node.locked} onDragStart={e=>e.dataTransfer.setData('text/cms-node',node.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop(e.dataTransfer.getData('text/cms-node'),node.id)}}>
  <button className="composer-layer-expand" disabled={!hasChildren} onClick={()=>toggle(node.id)}>{hasChildren?(open?<IconChevronDown size={14}/>:<IconChevronRight size={14}/>):<span/>}</button>
  <button className="composer-layer-name" onClick={()=>select(node.id)}>{node.locked&&<IconLock size={13}/>}<span>{node.name}</span><small>{node.type}</small></button>
  <button title={node.visible?'Hide':'Show'} onClick={()=>action('visibility',node.id)}>{node.visible?<IconEye size={14}/>:<IconEyeOff size={14}/>}</button><button title="Duplicate" onClick={()=>action('duplicate',node.id)}><IconCopy size={14}/></button><button title="Delete" disabled={node.locked} onClick={()=>action('delete',node.id)}><IconTrash size={14}/></button>
 </div>{open&&<div className="composer-layer-children">{node.children.map(child=><Layer key={child.id} {...{node:child,selected,expanded,toggle,select,action,drop}}/>)}</div>}</div>;
}

export function EditorPage(){
 const {key=''}=useParams();
 const [searchParams]=useSearchParams();
 const [page,setPage]=useState<ControlPage|null>(null),[data,setData]=useState<ContentData|null>(null),[saved,setSaved]=useState<ContentData|null>(null);
 const [revisionId,setRevisionId]=useState<string|null>(null),[versions,setVersions]=useState<Revision[]>([]),[selected,setSelected]=useState('hero');
 const [tab,setTab]=useState<'content'|'layout'|'style'|'advanced'|'seo'|'history'>('content'),[viewport,setViewport]=useState<Viewport>('desktop');
 const [status,setStatus]=useState('Loading page…'),[error,setError]=useState(''),[saving,setSaving]=useState(false),[review,setReview]=useState<ReleaseReview|null>(null);
 const [source,setSource]=useState<{sourceUrl:string;html:string}|null>(null),[frameReady,setFrameReady]=useState(0),[past,setPast]=useState<ContentData[]>([]),[future,setFuture]=useState<ContentData[]>([]);
 const [expanded,setExpanded]=useState(new Set(['hero','introduction'])),[layerSearch,setLayerSearch]=useState(''),[insertOpen,setInsertOpen]=useState(false),[insertSearch,setInsertSearch]=useState('');
 const frameRef=useRef<HTMLIFrameElement>(null),dirty=Boolean(data&&saved&&JSON.stringify(data)!==JSON.stringify(saved));
 const composition=data?.composition??(data&&page?compositionFromLegacy(page.label,data):undefined),selectedNode=composition?findNode(composition,selected):undefined;
 const previewHtml=source?.html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<meta\b(?=[^>]*http-equiv\s*=\s*["'](?:Content-Security-Policy|refresh)["'])[^>]*>/gi,'').replace(/<head([^>]*)>/i,`<head$1><base href="${source.sourceUrl.replace(/"/g,'&quot;')}">`);
 const commit=(next:Composition,message='Unsaved composition changes')=>{if(!data)return;setPast(items=>[...items.slice(-39),copy(data)]);setFuture([]);setData({...data,composition:next});setStatus(message)};
 const mutate=(id:string,fn:(node:CompositionNode)=>void)=>composition&&commit(updateNode(composition,id,fn));

 useEffect(()=>{let live=true;setData(null);setError('');void Promise.all([controlApi.pages(),controlApi.document(key),controlApi.versions(key),controlApi.pageSource(key)]).then(([catalog,result,history,pageSource])=>{if(!live)return;const found=catalog.pages.find(item=>item.key===key)??null,draft=result.document.currentDraftRevision;setPage(found);if(draft?.data&&found){const original=copy(draft.data),next=copy(draft.data);next.composition??=compositionFromLegacy(found.label,next);setData(next);setSaved(original);setRevisionId(draft.id);const requested=searchParams.get('select');setSelected(requested&&findNode(next.composition,requested)?requested:next.composition.root.children[0]?.id??'');setStatus(original.composition?'Saved draft':'Migrating page composition…')}setVersions(history.revisions);setSource(pageSource);if(!draft)setStatus('No imported draft')}).catch(cause=>live&&setError(apiErrorMessage(cause)));return()=>{live=false}},[key,searchParams]);
 useEffect(()=>{const doc=frameRef.current?.contentDocument;if(!doc||!composition)return;renderComposition(doc,composition,viewport,setSelected,(id,field,value)=>mutate(id,node=>{node.content[field]=value}),selected,(id,change)=>mutate(id,node=>{if(change.span!==undefined)setResponsiveLayout(node,viewport,'span',change.span);if(change.minHeight!==undefined){setResponsiveLayout(node,viewport,'height','custom');setResponsiveLayout(node,viewport,'minHeight',change.minHeight)}}),(sourceId,targetId)=>commit(reorder(composition,sourceId,targetId),'Reordered on canvas'))},[composition,viewport,selected,frameReady]);
 useEffect(()=>{if(!dirty||saving)return;const timer=window.setTimeout(()=>void save(),1800);return()=>clearTimeout(timer)},[data,saved,saving]);
 const save=async()=>{if(!data||!dirty||saving)return;const snapshot=copy(data);setSaving(true);setError('');setStatus('Saving…');try{const result=await controlApi.save(key,snapshot,revisionId);setRevisionId(result.revision.id);setSaved(snapshot);setVersions((await controlApi.versions(key)).revisions);setStatus('Saved draft')}catch(cause){setError(isApiError(cause)&&cause.code==='REVISION_CONFLICT'?'This draft changed elsewhere. Reload before saving.':apiErrorMessage(cause));setStatus('Save failed')}finally{setSaving(false)}};
 const undo=()=>{if(!data||!past.length)return;setFuture(items=>[copy(data),...items]);setData(past.at(-1)!);setPast(past.slice(0,-1));setStatus('Undo applied')},redo=()=>{if(!data||!future.length)return;setPast(items=>[...items,copy(data)]);setData(future[0]);setFuture(future.slice(1));setStatus('Redo applied')};
 const action=(name:string,id:string)=>{if(!composition)return;try{if(name==='visibility')commit(updateNode(composition,id,n=>{n.visible=!n.visible}));if(name==='duplicate')commit(duplicateNode(composition,id));if(name==='delete'){commit(removeNode(composition,id));setSelected(composition.root.children[0]?.id??'')}if(name==='up')commit(moveNode(composition,id,-1));if(name==='down')commit(moveNode(composition,id,1))}catch(cause){setError(cause instanceof Error?cause.message:'Composition change failed')}};
 const insert=(type:ComponentType)=>{if(!composition)return;const node=makeNode(type);try{const parent=selectedNode&&componentRegistry[selectedNode.type].children.includes(type)?selectedNode.id:undefined;commit(insertNode(composition,node,parent));setSelected(node.id);if(parent)setExpanded(items=>new Set([...items,parent]));setInsertOpen(false)}catch(cause){setError(cause instanceof Error?cause.message:'Invalid nesting')}};
 const openReview=async()=>{if(!revisionId||dirty){setError('Save the draft before review.');return}try{setReview((await controlApi.review(key,revisionId)).review)}catch(cause){setError(apiErrorMessage(cause))}},publish=async()=>{if(!revisionId||!review?.valid)return;try{await controlApi.publish(key,revisionId);setReview(null);setStatus('Release queued for website deployment')}catch(cause){setError(apiErrorMessage(cause))}};
 const restore=async(id:string)=>{try{const result=await controlApi.restore(key,id),next=copy(result.revision.data);if(page)next.composition??=compositionFromLegacy(page.label,next);setData(next);setSaved(copy(next));setRevisionId(result.revision.id);setVersions((await controlApi.versions(key)).revisions);setStatus('Revision restored as a new draft')}catch(cause){setError(apiErrorMessage(cause))}};
 const toggle=(id:string)=>setExpanded(items=>{const next=new Set(items);next.has(id)?next.delete(id):next.add(id);return next}),roots=useMemo(()=>composition?.root.children.filter(node=>!layerSearch||JSON.stringify(node).toLowerCase().includes(layerSearch.toLowerCase()))??[],[composition,layerSearch]);
 if(!page&&!error)return <div className="control-loading">Loading visual editor…</div>;if(!page)return <div className="control-error">{error||'Page not found'} <Link to="/control/pages">Back to pages</Link></div>;
 return <div className="control-editor composer"><header className="control-editor-top"><div><Link className="control-back" to="/control/pages"><IconArrowLeft size={16}/>Pages</Link><h1>{page.label}</h1><span className={`control-save-state${dirty?' is-dirty':''}`}>{status}</span></div><div className="control-editor-actions"><button className="control-button" disabled={!past.length} onClick={undo}>↶</button><button className="control-button" disabled={!future.length} onClick={redo}>↷</button><button className="control-button" disabled={!dirty||saving} onClick={()=>void save()}><IconDeviceFloppy size={16}/>Save draft</button><button className="control-button primary" disabled={dirty||!revisionId} onClick={()=>void openReview()}>Review release</button></div></header>
 {error&&<div className="control-error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {!data||!composition?<div className="control-empty">No imported draft is available.</div>:<div className="control-editor-grid composer-grid">
  <aside className="control-editor-layers composer-layers"><div className="composer-pane-title"><div><h2>Layers</h2><p>{composition.root.children.length} page sections</p></div><button title="Insert component" onClick={()=>setInsertOpen(true)}><IconPlus size={18}/></button></div><label className="composer-search"><IconSearch size={15}/><input value={layerSearch} onChange={e=>setLayerSearch(e.target.value)} placeholder="Search layers"/></label><div className="composer-page-root"><strong>Page · {page.label}</strong>{roots.map(node=><Layer key={node.id} node={node} selected={selected} expanded={expanded} toggle={toggle} select={setSelected} action={action} drop={(sourceId,targetId)=>commit(reorder(composition,sourceId,targetId))}/>)}</div><button className="composer-add-section" onClick={()=>setInsertOpen(true)}><IconPlus size={16}/> Add section</button></aside>
  <section className="control-canvas"><div className="control-canvas-toolbar"><div><strong>Live website canvas</strong><span>Click to select · double click text to edit · drag sections to reorder</span></div><div className="control-viewport">{([['desktop',IconDeviceDesktop],['tablet',IconDeviceTablet],['mobile',IconDeviceMobile]] as const).map(([value,Icon])=><button key={value} aria-label={`${value} preview`} aria-pressed={viewport===value} onClick={()=>setViewport(value)}><Icon size={18}/></button>)}</div></div><div className="control-canvas-stage composer-stage">{previewHtml?<iframe ref={frameRef} title={`${page.label} website composition`} srcDoc={previewHtml} sandbox="allow-same-origin" onLoad={()=>setFrameReady(value=>value+1)} className={`control-site-frame ${viewport}`}/>:<div className="control-empty">Loading actual website…</div>}<div className="composer-canvas-actions"><button onClick={()=>action('up',selected)}>Move up</button><button onClick={()=>action('down',selected)}>Move down</button><button onClick={()=>action('duplicate',selected)}>Duplicate</button><button onClick={()=>action('visibility',selected)}>{selectedNode?.visible?'Hide':'Show'}</button><button disabled={selectedNode?.locked} onClick={()=>action('delete',selected)}>Delete</button></div></div></section>
  <aside className="control-inspector composer-inspector"><div className="control-inspector-tabs composer-tabs">{(['content','layout','style','advanced','seo','history'] as const).map(value=><button key={value} className={tab===value?'is-active':''} onClick={()=>setTab(value)}>{value}</button>)}</div>{selectedNode&&tab!=='seo'&&tab!=='history'&&<Inspector node={selectedNode} viewport={viewport} tab={tab} data={data} mutate={fn=>mutate(selectedNode.id,fn)}/>} {tab==='seo'&&<Seo data={data} setData={next=>{setPast(items=>[...items,copy(data)]);setData(next)}}/>}{tab==='history'&&<History versions={versions} current={revisionId} data={data} restore={restore}/>}</aside>
 </div>}{insertOpen&&<InsertPanel query={insertSearch} setQuery={setInsertSearch} insert={insert} close={()=>setInsertOpen(false)}/>} {review&&<Review review={review} close={()=>setReview(null)} publish={publish}/>}</div>;
}

function Inspector({node,viewport,tab,data,mutate}:{node:CompositionNode;viewport:Viewport;tab:'content'|'layout'|'style'|'advanced';data:ContentData;mutate:(fn:(node:CompositionNode)=>void)=>void}){
 const layout=effectiveLayout(node,viewport),override=viewport!=='desktop'&&Boolean(node.responsive[viewport]?.layout);
 const field=(label:string,name:keyof CompositionNode['content'],multiline=false)=><label>{label}{multiline?<textarea rows={5} value={String(node.content[name]??'')} onChange={e=>mutate(n=>{(n.content as Record<string,unknown>)[name]=e.target.value})}/>:<input value={String(node.content[name]??'')} onChange={e=>mutate(n=>{(n.content as Record<string,unknown>)[name]=e.target.value})}/>}</label>;
 return <div className="control-inspector-content"><div className="composer-inspector-heading"><div><small>{node.type}</small><h2>{node.name}</h2></div>{node.locked&&<IconLock size={17}/>}</div>
 {tab==='content'&&<>{field('Heading','heading')}{field('Body','body',true)}{field('Text','text',true)}{(node.content.src!==undefined||['image','video','image-card','service-card'].includes(node.type))&&<>{field('Media URL','src')}{field('Alternative text','alt')}</>}{(node.content.label!==undefined||['button','link','cta'].includes(node.type))&&<><h3>Button / link</h3>{field('Label','label')}<label>Action<select value={node.content.action??'internal'} onChange={e=>mutate(n=>{n.content.action=e.target.value as NonNullable<typeof n.content.action>})}>{['internal','external','email','telephone','anchor','file'].map(v=><option key={v}>{v}</option>)}</select></label>{field('Destination','href')}{node.content.href&&!safeLink(node.content.href,node.content.action)&&<p className="composer-validation">Enter a safe destination for this action.</p>}<label>Open<select value={node.content.target??'same'} onChange={e=>mutate(n=>{n.content.target=e.target.value as 'same'|'new'})}><option value="same">Same tab</option><option value="new">New tab</option></select></label></>}{data.media.length>0&&<label>Choose page media<select value="" onChange={e=>mutate(n=>{n.content.src=e.target.value})}><option value="">Select media…</option>{data.media.map((media,index)=><option key={`${media.src}-${index}`} value={media.src}>{media.alt||media.src}</option>)}</select></label>}</>}
 {tab==='layout'&&<><div className="composer-inheritance"><span>{viewport==='desktop'?'Base layout':override?'Override':'Inherited from desktop'}</span>{viewport!=='desktop'&&override&&<button onClick={()=>mutate(n=>resetResponsive(n,viewport))}>Reset to inherited</button>}</div><label>Grid span<select value={layout.span??12} onChange={e=>mutate(n=>setResponsiveLayout(n,viewport,'span',Number(e.target.value)))}>{[3,4,6,8,12].map(v=><option value={v} key={v}>{v} / 12 · {Math.round(v/12*100)}%</option>)}</select></label><label>Columns<input type="number" min="1" max="12" value={layout.columns??1} onChange={e=>mutate(n=>setResponsiveLayout(n,viewport,'columns',Number(e.target.value)))}/></label><label>Height<select value={layout.height??'fit'} onChange={e=>mutate(n=>setResponsiveLayout(n,viewport,'height',e.target.value as NodeLayout['height']))}>{['fit','small','medium','large','viewport','custom'].map(v=><option key={v}>{v}</option>)}</select></label>{layout.height==='custom'&&<label>Minimum height<input type="number" min="0" max="2000" value={layout.minHeight??0} onChange={e=>mutate(n=>setResponsiveLayout(n,viewport,'minHeight',Number(e.target.value)))}/></label>}<label>Gap<select value={layout.gap??'md'} onChange={e=>mutate(n=>setResponsiveLayout(n,viewport,'gap',e.target.value as NodeLayout['gap']))}>{['none','xs','sm','md','lg','xl'].map(v=><option key={v}>{v}</option>)}</select></label></>}
 {tab==='style'&&<><label>Approved background<select value={node.style.background} onChange={e=>mutate(n=>{n.style.background=e.target.value as typeof n.style.background})}>{['none','white','light','deep-blue','light-blue','yellow','brand-gradient','image'].map(v=><option key={v}>{v}</option>)}</select></label>{node.style.background==='image'&&<>{field('Background image','src')}<label>Overlay {Math.round((node.style.overlay??0)*100)}%<input type="range" min="0" max="1" step=".05" value={node.style.overlay??0} onChange={e=>mutate(n=>{n.style.overlay=Number(e.target.value)})}/></label></>}<label>Radius<select value={node.style.radius} onChange={e=>mutate(n=>{n.style.radius=e.target.value as typeof n.style.radius})}>{['none','sm','md','lg'].map(v=><option key={v}>{v}</option>)}</select></label><label>Media fit<select value={node.style.fit??'cover'} onChange={e=>mutate(n=>{n.style.fit=e.target.value as 'cover'|'contain'})}><option>cover</option><option>contain</option></select></label><label>Focal point X<input type="range" min="0" max="100" value={node.style.focalX??50} onChange={e=>mutate(n=>{n.style.focalX=Number(e.target.value)})}/></label></>}
 {tab==='advanced'&&<><label>Layer name<input value={node.name} onChange={e=>mutate(n=>{n.name=e.target.value})}/></label><label>Element key<input value={node.key} onChange={e=>mutate(n=>{n.key=e.target.value})}/></label><label className="control-check"><input type="checkbox" checked={node.visible} onChange={()=>mutate(n=>{n.visible=!n.visible})}/> Visible</label><label>Reusable instance key<input value={node.reusableKey??''} onChange={e=>mutate(n=>{n.reusableKey=e.target.value||undefined})} placeholder="Optional shared component key"/></label><h3>Global data reference</h3><label>Canonical key<input value={node.content.reference?.key??''} onChange={e=>mutate(n=>{n.content.reference=e.target.value?{key:e.target.value,state:'linked',snapshot:n.content.reference?.snapshot}:undefined})} placeholder="group.employee_count"/></label>{node.content.reference&&<label>Reference state<select value={node.content.reference.state} onChange={e=>mutate(n=>{if(n.content.reference)n.content.reference.state=e.target.value as typeof n.content.reference.state})}>{['linked','override','detached','broken'].map(value=><option key={value}>{value}</option>)}</select></label>}<p className="control-inspector-hint">{node.locked?'This production component is protected from deletion.':'Stored in the structured composition revision.'}</p></>}</div>;
}

function InsertPanel({query,setQuery,insert,close}:{query:string;setQuery:(v:string)=>void;insert:(type:ComponentType)=>void;close:()=>void}){const entries=(Object.entries(componentRegistry) as [ComponentType,(typeof componentRegistry)[ComponentType]][]).filter(([,v])=>v.label.toLowerCase().includes(query.toLowerCase()));return <div className="control-review-backdrop" onMouseDown={close}><section className="composer-insert" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><small>Component library</small><h2>Add to page</h2></div><button onClick={close}>Close</button></header><label className="composer-search"><IconSearch size={17}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search components"/></label>{['Layout','Content','Lake components','Media','Advanced'].map(category=><div className="composer-library" key={category}><h3>{category}</h3><div>{entries.filter(([,v])=>v.category===category).map(([type,v])=><button key={type} onClick={()=>insert(type)}><span className="composer-thumbnail">{v.label[0]}</span><strong>{v.label}</strong><small>{type}</small></button>)}</div></div>)}</section></div>}
function Seo({data,setData}:{data:ContentData;setData:(d:ContentData)=>void}){
 const update=(field:keyof ContentData['seo'],value:string|boolean)=>setData({...data,seo:{...data.seo,[field]:value}});
 return <div className="control-inspector-content"><h2>Search appearance</h2>
  <label>Page title<input maxLength={160} value={data.seo.title} onChange={e=>update('title',e.target.value)}/></label>
  <label>Description<textarea rows={5} maxLength={320} value={data.seo.description} onChange={e=>update('description',e.target.value)}/></label>
  <label>Canonical URL<input value={data.seo.canonical??''} onChange={e=>update('canonical',e.target.value)}/></label>
  <h3>Social sharing</h3>
  <label>Open Graph title<input maxLength={160} value={data.seo.ogTitle??''} placeholder="Use page title" onChange={e=>update('ogTitle',e.target.value)}/></label>
  <label>Open Graph description<textarea rows={3} maxLength={320} value={data.seo.ogDescription??''} placeholder="Use page description" onChange={e=>update('ogDescription',e.target.value)}/></label>
  <label>Social image URL<input value={data.seo.socialImage??''} onChange={e=>update('socialImage',e.target.value)}/></label>
  {data.media.length>0&&<label>Choose page image<select value="" onChange={e=>update('socialImage',e.target.value)}><option value="">Select media…</option>{data.media.filter(item=>item.role!=='download').map((item,index)=><option key={`${item.src}-${index}`} value={item.src}>{item.alt||item.src}</option>)}</select></label>}
  <h3>Indexability</h3><label className="control-check"><input type="checkbox" checked={data.seo.index!==false} onChange={e=>{if(!e.target.checked&&!window.confirm('Exclude this page from search engines? The release review will flag this change.'))return;update('index',e.target.checked)}}/> Allow search engines to index this page</label>
  <p className="control-inspector-hint">Indexability is per page. The Home page cannot be published as noindex.</p>
 </div>;
}
function History({versions,current,data,restore}:{versions:Revision[];current:string|null;data:ContentData;restore:(id:string)=>Promise<void>}){return <div className="control-inspector-content"><h2>Composition history</h2>{versions.map(version=>{const changes=compositionDiff(version.data.composition,data.composition);return <div className="control-version" key={version.id}><strong>{new Date(version.createdAt).toLocaleString()}</strong><small>{changes.length?`${changes.length} structured changes`:'Legacy content revision'}</small>{changes.slice(0,3).map((c,i)=><small key={i}>{c.kind}: {c.label}</small>)}{version.id!==current&&<button onClick={()=>void restore(version.id)}><IconRefresh size={14}/> Restore as draft</button>}</div>})}</div>}
function Review({review,close,publish}:{review:ReleaseReview;close:()=>void;publish:()=>Promise<void>}){return <div className="control-review-backdrop"><section className="control-review-dialog" role="dialog" aria-modal="true" aria-label="Review structured changes"><div className="control-review-header"><div><small>Release review</small><h2>Review structured changes</h2><p>{review.changedFields} changed fields</p></div><button onClick={close}>Close</button></div><div className="control-review-issues">{review.issues.map((issue,i)=><p className={issue.severity} key={i}><strong>{issue.severity}</strong> {issue.message}</p>)}</div><div className="control-review-changes">{review.changes.slice(0,30).map(change=><div className="control-review-change" key={change.field}><strong>{change.field}</strong><div><span>{change.before}</span><span>{change.after}</span></div></div>)}</div><div className="control-review-footer"><span>Creates an immutable, verified release.</span><button className="control-button primary" disabled={!review.valid} onClick={()=>void publish()}>Create release</button></div></section></div>}
