import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { IconArrowRight, IconCircleCheck, IconExternalLink, IconFileText, IconHistory, IconPhoto, IconSitemap } from '@tabler/icons-react';
import { apiErrorMessage } from '../../services/api';
import { controlApi, publicSiteBase } from './api';

export function OverviewPage() {
  const pages = useQuery({ queryKey: ['control-pages'], queryFn: controlApi.pages });
  const releases = useQuery({ queryKey: ['control-releases'], queryFn: controlApi.releases });
  const changed = pages.data?.pages.filter((page) => page.draftRevisionId && page.draftRevisionId !== page.publishedRevisionId) ?? [];
  const recent = [...(pages.data?.pages ?? [])].filter((page) => page.updatedAt).sort((a, b) => new Date(b.updatedAt!).getTime() - new Date(a.updatedAt!).getTime()).slice(0, 5);
  return <div className="control-page">
    <div className="control-page-heading"><div><p className="control-eyebrow">Overview</p><h1>Website control center</h1><p>Content status and the work that needs attention.</p></div><a className="control-button" href={publicSiteBase} target="_blank" rel="noreferrer">Open website <IconExternalLink size={16} /></a></div>
    {pages.isLoading ? <div className="control-loading" role="status">Loading website status…</div> : pages.error ? <div className="control-error" role="alert">{apiErrorMessage(pages.error)} <button onClick={() => void pages.refetch()}>Retry</button></div> : <>
      <div className="control-status-strip"><div><small>Registered pages</small><strong>{pages.data?.pages.length ?? 0}</strong><span>Current site catalog</span></div><div><small>Drafts to review</small><strong>{changed.length}</strong><span>{changed.length ? 'Saved changes await publishing' : 'No pending page changes'}</span></div><div><small>Latest CMS release</small><strong>{releases.data?.releases[0] ? new Date(releases.data.releases[0].publishedAt).toLocaleDateString() : 'None'}</strong><span>{releases.isLoading ? 'Checking releases…' : releases.error ? 'Status unavailable' : 'Immutable release history'}</span></div></div>
      <div className="control-overview-grid"><section className="control-panel"><div className="control-panel-heading"><div><h2>Needs attention</h2><p>Drafts that differ from their published revision</p></div><Link to="/control/pages">All pages <IconArrowRight size={16} /></Link></div>{changed.length ? <div className="control-list">{changed.slice(0, 8).map((page) => <Link to={`/control/pages/${page.key}`} key={page.key} className="control-list-row"><IconFileText size={18} /><span><strong>{page.label}</strong><small>{page.route}</small></span><span className="control-status changed">Changed</span><IconArrowRight size={16} /></Link>)}</div> : <div className="control-empty"><IconCircleCheck size={22} /><strong>No page drafts need attention</strong><span>Saved edits will appear here.</span></div>}</section><section className="control-panel"><div className="control-panel-heading"><div><h2>Quick actions</h2><p>Open the workspace you need</p></div></div><div className="control-quick-actions"><Link to="/control/pages"><IconFileText size={19} /> Manage pages <IconArrowRight size={16} /></Link><Link to="/control/navigation"><IconSitemap size={19} /> Edit navigation <IconArrowRight size={16} /></Link><Link to="/app/media"><IconPhoto size={19} /> Open media library <IconArrowRight size={16} /></Link><Link to="/control/history"><IconHistory size={19} /> Review versions <IconArrowRight size={16} /></Link></div></section></div>
      <section className="control-panel"><div className="control-panel-heading"><div><h2>Recently edited pages</h2><p>Based on saved CMS revisions</p></div></div>{recent.length ? <div className="control-list">{recent.map((page) => <Link to={`/control/pages/${page.key}`} key={page.key} className="control-list-row"><IconFileText size={18} /><span><strong>{page.label}</strong><small>{page.route}</small></span><time>{new Date(page.updatedAt!).toLocaleString()}</time><IconArrowRight size={16} /></Link>)}</div> : <div className="control-empty">No CMS revisions have been saved yet.</div>}</section>
    </>}
  </div>;
}
